import {colors} from '../../theme/colors';
import {select} from '../../theme/device';
import {ms as baseMs, vs as baseVs} from '../../theme/scale';

const PHONE_FACTOR = select({phone: 0.82, tablet: 1});
export const ms = n => baseMs(n) * PHONE_FACTOR;
export const vs = n => baseVs(n) * PHONE_FACTOR;

// sort caret next to sortable header labels
export const SORT_ICON = select({phone: 9, tablet: 12});

export const MODES = ['All Modes', 'FTL', 'LTL'];

export const STATS = [
  {label: 'Currently Leading', value: '2', note: 'Across Active Bids', accent: colors.warning_text, labelColor: colors.warning_text},
  {label: 'Active Bids', value: '6', note: 'in Progress', accent: colors.accentBlue, labelColor: colors.accentBlue},
  {label: 'Awarded Bids', value: '1', note: '8% vs last week', accent: colors.success, labelColor: colors.success, noteColor: colors.success, up: true},
  {label: 'Open Auction', value: '637', note: 'Across All Modes', accent: colors.card_drive_load, labelColor: colors.card_drive_load},
];

export const STATUS = {
  Awarded: {text: colors.success_text, bg: colors.success_bg},
  Open: {text: colors.button_color, bg: '#FEE9CF'},
};

export const BIDS = [
  {
    id: 'b1',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: '#4 you',
    bids: 2,
    status: 'Awarded',
    awardedAt: '$900',
  },
  {
    id: 'b2',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: null,
    bids: 2,
    status: 'Open',
    awardedAt: null,
  },
  {
    id: 'b3',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: null,
    bids: 2,
    status: 'Open',
    awardedAt: null,
  },
  {
    id: 'b4',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: null,
    bids: 2,
    status: 'Open',
    awardedAt: null,
  },
  {
    id: 'b5',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: null,
    bids: 2,
    status: 'Open',
    awardedAt: null,
  },
  {
    id: 'b6',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: null,
    bids: 2,
    status: 'Open',
    awardedAt: null,
  },
  {
    id: 'b7',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: null,
    bids: 2,
    status: 'Open',
    awardedAt: null,
  },
  {
    id: 'b8',
    origin: 'San Jose CA',
    dest: 'Newark NJ',
    ref: 'FTL – 09010',
    mode: 'FTL',
    date: 'Feb, 28',
    time: '6:00 PM',
    pickupTime: '6.00Pm',
    pickupDate: '28th July',
    indicative: '$4567',
    amount: '$1100',
    lowestBid: '$4567',
    rank: null,
    bids: 2,
    status: 'Open',
    awardedAt: null,
  },
];
