import {StyleSheet} from 'react-native';
import {moderateScale, scale, verticalScale} from 'react-native-size-matters';
import {colors} from '../theme/colors';

export default StyleSheet.create({
  searchCard: {
    position: 'absolute',
    top: verticalScale(5),
    left: scale(5),
    right: scale(5),
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderRadius: moderateScale(20),
    padding: moderateScale(15),
    elevation: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.2,
    shadowRadius: moderateScale(12),
    zIndex: 30,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(6),
    gap: scale(6),
  },
  labelText: {
    fontSize: moderateScale(20),
    fontWeight: '700',
    color: colors.muted,
  },
  searchInputContainer: {
    position: 'relative',
    zIndex: 20,
    marginBottom: verticalScale(6),
  },
  searchInputContainerActive: {
    zIndex: 200,
  },
  searchInput: {
    height: verticalScale(40),
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: moderateScale(12),
    paddingHorizontal: scale(50),
    fontSize: moderateScale(15),
    backgroundColor: '#FAFAFA',
    marginBottom: verticalScale(10),
    fontWeight: '500',
    color: '#334155',
  },
  searchInputActive: {
    borderColor: '#3B82F6',
    backgroundColor: '#F0F9FF',
  },
  swapIconLeft: {
    position: 'absolute',
    left: scale(10),
    top: verticalScale(4),
    padding: scale(6),
    zIndex: 30,
    borderRadius: moderateScale(8),
  },
  loadingIndicator: {
    position: 'absolute',
    right: scale(10),
    top: verticalScale(12),
  },
  suggestionList: {
    position: 'absolute',
    top: verticalScale(52),
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderRadius: moderateScale(8),
    elevation: 14,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.2,
    shadowRadius: moderateScale(10),
    maxHeight: verticalScale(220),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
  },
  suggestionItem: {
    padding: moderateScale(12),
    borderBottomWidth: moderateScale(1),
    borderColor: '#eee',
  },
  suggestionTitle: {
    fontSize: moderateScale(14),
    color: '#333',
    fontWeight: '600',
  },
  suggestionAddress: {
    fontSize: moderateScale(12),
    color: '#64748B',
    marginTop: verticalScale(4),
  },
  routeCard: {
    marginTop: verticalScale(10),
    padding: moderateScale(12),
    borderRadius: moderateScale(14),
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#DCE7F5',
  },
  routeHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  routeTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: colors.primary,
  },
  routeBadge: {
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
  },
  routeBadgeText: {
    fontSize: moderateScale(11),
    fontWeight: '700',
    color: '#2563EB',
  },
  routeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: verticalScale(8),
    marginBottom: verticalScale(10),
  },
  routeInfoItem: {
    width: '48%',
    padding: moderateScale(10),
    borderRadius: moderateScale(10),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  routeInfoLabel: {
    fontSize: moderateScale(11),
    color: '#64748B',
    marginBottom: verticalScale(3),
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  routeInfoValue: {
    fontSize: moderateScale(13),
    color: '#0F172A',
    fontWeight: '700',
  },
  routeError: {
    marginTop: verticalScale(10),
    padding: moderateScale(10),
    borderRadius: moderateScale(10),
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    color: '#B91C1C',
  },
  routeLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    marginTop: verticalScale(10),
    padding: moderateScale(10),
    borderRadius: moderateScale(10),
    backgroundColor: '#EFF6FF',
  },
  routeLoadingText: {
    color: '#1D4ED8',
    fontWeight: '600',
  },
  responseContainer: {
    marginTop: verticalScale(4),
    padding: moderateScale(10),
    borderRadius: moderateScale(10),
    backgroundColor: '#0F172A',
    maxHeight: verticalScale(180),
  },
  responseTitle: {
    color: '#F8FAFC',
    fontSize: moderateScale(12),
    fontWeight: '700',
    marginBottom: verticalScale(6),
  },
  responseText: {
    color: '#CBD5E1',
    fontSize: moderateScale(11),
    lineHeight: moderateScale(16),
  },
});
