import {StyleSheet} from 'react-native';
import {moderateScale, scale, verticalScale} from 'react-native-size-matters';
import {colors} from '../theme/colors';

export default StyleSheet.create({
  overlayRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  backgroundMapLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  searchCardStack: {
    position: 'absolute',
    top: verticalScale(8),
    left: scale(8),
    right: scale(8),
    zIndex: 30,
  },
  searchCardScroll: {
    flexGrow: 1,
  },
  searchCardContent: {
    paddingBottom: verticalScale(6),
  },
  floatingSectionCard: {
    padding: moderateScale(12),
    borderRadius: moderateScale(20),
    backgroundColor: 'rgba(255,255,255,0.98)',
    marginBottom: verticalScale(8),
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.16,
    shadowRadius: moderateScale(10),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  topHandle: {
    width: scale(44),
    height: verticalScale(5),
    borderRadius: moderateScale(999),
    backgroundColor: '#D0D5DD',
    alignSelf: 'center',
    marginBottom: verticalScale(10),
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(6),
    gap: scale(6),
  },
  labelRowCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(6),
    gap: scale(6),
  },
  labelText: {
    fontSize: moderateScale(17),
    fontWeight: '700',
    color: '#1D2939',
  },
  searchInputContainer: {
    position: 'relative',
    zIndex: 20,
    marginBottom: verticalScale(6),
  },
  searchInputContainerActive: {
    zIndex: 200,
  },
  searchInput: {
    height: verticalScale(40),
    borderWidth: 1.6,
    borderColor: '#344054',
    borderRadius: moderateScale(14),
    paddingHorizontal: scale(44),
    fontSize: moderateScale(14),
    backgroundColor: '#FFFFFF',
    marginBottom: verticalScale(8),
    fontWeight: '500',
    color: '#334155',
  },
  searchInputActive: {
    borderColor: '#3B82F6',
    backgroundColor: '#F8FBFF',
  },
  swapIconLeft: {
    position: 'absolute',
    left: scale(10),
    top: verticalScale(4),
    padding: scale(6),
    zIndex: 30,
    borderRadius: moderateScale(8),
  },
  loadingIndicator: {
    position: 'absolute',
    right: scale(10),
    top: verticalScale(12),
  },
  suggestionList: {
    position: 'relative',
    backgroundColor: '#fff',
    borderRadius: moderateScale(12),
    elevation: 14,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.2,
    shadowRadius: moderateScale(10),
    maxHeight: verticalScale(220),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    marginTop: verticalScale(-2),
    marginBottom: verticalScale(8),
  },
  suggestionItem: {
    padding: moderateScale(12),
    borderBottomWidth: moderateScale(1),
    borderColor: '#eee',
  },
  suggestionTitle: {
    fontSize: moderateScale(14),
    color: '#333',
    fontWeight: '600',
  },
  suggestionAddress: {
    fontSize: moderateScale(12),
    color: '#64748B',
    marginTop: verticalScale(4),
  },
  routeSummaryCard: {
    marginTop: verticalScale(8),
    padding: moderateScale(12),
    borderRadius: moderateScale(18),
    backgroundColor: 'rgba(248, 250, 252, 0.96)',
    borderWidth: 1,
    borderColor: '#DCE7F5',
  },
  routeSummaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  routeHeaderBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  routeBadgeSmall: {
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(6),
    borderRadius: moderateScale(999),
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  routeBadgeSmallText: {
    fontSize: moderateScale(10),
    fontWeight: '700',
    color: '#1D4ED8',
  },
  routeTitle: {
    fontSize: moderateScale(14),
    fontWeight: '700',
    color: '#1D4ED8',
  },
  routeBadgeCompact: {
    paddingHorizontal: scale(9),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(999),
    backgroundColor: 'rgba(34, 197, 94, 0.14)',
  },
  routeBadgeText: {
    fontSize: moderateScale(11),
    fontWeight: '700',
    color: '#16A34A',
  },
  routeSummaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  routeInfoItemCompact: {
    width: '48%',
    padding: moderateScale(10),
    borderRadius: moderateScale(14),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  routeInfoLabel: {
    fontSize: moderateScale(11),
    color: '#64748B',
    marginBottom: verticalScale(3),
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  routeInfoValue: {
    fontSize: moderateScale(13),
    color: '#0F172A',
    fontWeight: '700',
  },
  routeError: {
    marginTop: verticalScale(10),
    padding: moderateScale(10),
    borderRadius: moderateScale(10),
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    color: '#B91C1C',
  },
  routeLoadingRowCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    marginTop: verticalScale(8),
    padding: moderateScale(10),
    borderRadius: moderateScale(14),
    backgroundColor: '#EFF6FF',
  },
  routeLoadingText: {
    color: '#1D4ED8',
    fontWeight: '600',
  },
  routeEmptyCard: {
    padding: moderateScale(14),
    marginBottom: verticalScale(10),
    borderRadius: moderateScale(18),
    borderWidth: 1,
    borderColor: '#DCE7F5',
    backgroundColor: '#F8FAFF',
  },
  routeEmptyTitle: {
    fontSize: moderateScale(14),
    color: '#1D4ED8',
    fontWeight: '700',
    marginBottom: verticalScale(6),
  },
  routeEmptyText: {
    fontSize: moderateScale(12),
    color: '#475569',
    lineHeight: moderateScale(18),
  },
  responseContainer: {
    marginTop: verticalScale(4),
    padding: moderateScale(10),
    borderRadius: moderateScale(10),
    backgroundColor: '#0F172A',
    maxHeight: verticalScale(180),
  },
  responseTitle: {
    color: '#F8FAFC',
    fontSize: moderateScale(12),
    fontWeight: '700',
    marginBottom: verticalScale(6),
  },
  responseText: {
    color: '#CBD5E1',
    fontSize: moderateScale(11),
    lineHeight: moderateScale(16),
  },
  routeMessageCard: {
    marginTop: verticalScale(10),
    padding: moderateScale(12),
    borderRadius: moderateScale(14),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DCE7F5',
  },
  routeMessageTitle: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: '#1D4ED8',
    marginBottom: verticalScale(6),
  },
  routeMessageText: {
    fontSize: moderateScale(12),
    lineHeight: moderateScale(18),
    color: '#334155',
    fontWeight: '500',
  },
  routeInfoScroller: {
    paddingTop: verticalScale(8),
    paddingBottom: verticalScale(2),
    paddingRight: scale(12),
  },
  routeInfoPill: {
    minWidth: scale(82),
    marginRight: scale(8),
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(8),
    borderRadius: moderateScale(14),
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  routeInfoPillWide: {
    minWidth: scale(150),
    marginRight: scale(8),
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(8),
    borderRadius: moderateScale(14),
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  routeInfoPillLabel: {
    fontSize: moderateScale(10),
    color: '#64748B',
    fontWeight: '700',
    marginBottom: verticalScale(4),
    textTransform: 'uppercase',
  },
  routeInfoPillValue: {
    fontSize: moderateScale(12),
    color: '#0F172A',
    fontWeight: '700',
  },
  pillButton: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: moderateScale(999),
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(6),
    marginRight: scale(8),
    backgroundColor: '#FFFFFF',
  },
  pillButtonActive: {
    borderColor: '#2563EB',
    backgroundColor: '#DBEAFE',
  },
  pillText: {
    color: '#334155',
    fontSize: moderateScale(11),
    fontWeight: '600',
  },
  pillTextActive: {
    color: '#1D4ED8',
  },
  bottomControlsWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: verticalScale(88),
    zIndex: 35,
  },
  bottomControlsContent: {
    paddingHorizontal: scale(14),
  },
  pillButtonBottom: {
    borderWidth: 1,
    borderColor: '#D0D5DD',
    borderRadius: moderateScale(999),
    paddingHorizontal: scale(14),
    paddingVertical: verticalScale(10),
    marginRight: scale(10),
    backgroundColor: 'rgba(255,255,255,0.96)',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: moderateScale(4),
  },
  tollModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  tollModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: moderateScale(24),
    borderTopRightRadius: moderateScale(24),
    maxHeight: '70%',
    paddingTop: verticalScale(16),
  },
  tollModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(12),
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  tollModalTitle: {
    fontSize: moderateScale(16),
    fontWeight: '700',
    color: '#1D4ED8',
  },
  tollModalClose: {
    fontSize: moderateScale(24),
    color: '#94A3B8',
    fontWeight: '500',
  },
  tollModalScroll: {
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(12),
  },
  tollItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(12),
    marginBottom: verticalScale(8),
    borderRadius: moderateScale(12),
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  tollItemName: {
    fontSize: moderateScale(13),
    fontWeight: '600',
    color: '#1F2937',
    flex: 1,
  },
  tollItemAmount: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: '#1D4ED8',
  },
  tollItemTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: verticalScale(14),
    paddingHorizontal: scale(12),
    marginTop: verticalScale(8),
    marginBottom: verticalScale(12),
    borderRadius: moderateScale(14),
    backgroundColor: '#EFF6FF',
    borderWidth: 2,
    borderColor: '#BFDBFE',
  },
  tollItemTotalLabel: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: '#1D4ED8',
  },
  tollItemTotalAmount: {
    fontSize: moderateScale(14),
    fontWeight: '800',
    color: '#1D4ED8',
  },
  tollModalNote: {
    fontSize: moderateScale(11),
    color: '#64748B',
    fontStyle: 'italic',
    textAlign: 'center',
    paddingBottom: verticalScale(12),
  },
});
