import { StyleSheet } from 'react-native';
import { moderateScale, verticalScale, scale } from 'react-native-size-matters';
import { colors } from '../../theme/colors';

export default StyleSheet.create({
   container: {flex: 1, backgroundColor: '#0f172a'},
  map: {flex: 1},
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f172a',
  },
  loadingText: {color: '#94a3b8', fontSize: moderateScale(14)},
  searchCardWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  navInfoBar: {
    position: 'absolute',
    top: verticalScale(50),
    left: scale(12),
    right: scale(12),
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: moderateScale(14),
    paddingVertical: verticalScale(12),
    paddingHorizontal: scale(16),
    zIndex: 999,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    shadowColor: '#3b82f6',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  navInfoRow: {flexDirection: 'row', alignItems: 'center'},
  navInfoEta: {alignItems: 'center', minWidth: scale(50)},
  navInfoEtaText: {
    color: '#3b82f6',
    fontSize: moderateScale(28),
    fontWeight: '700',
  },
  navInfoEtaLabel: {
    color: '#64748b',
    fontSize: moderateScale(12),
    fontWeight: '500',
    marginTop: -2,
  },
  navInfoDivider: {
    width: 1,
    height: verticalScale(36),
    backgroundColor: '#1e293b',
    marginHorizontal: scale(12),
  },
  navInfoDetails: {flex: 1},
  navInfoDistText: {
    color: '#e2e8f0',
    fontSize: moderateScale(14),
    fontWeight: '600',
  },
  navInfoArrivalText: {
    color: '#64748b',
    fontSize: moderateScale(12),
    marginTop: 2,
  },
  navStopButton: {
    backgroundColor: '#dc2626',
    borderRadius: moderateScale(8),
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(14),
    marginLeft: scale(8),
  },
  navStopButtonText: {
    color: '#ffffff',
    fontSize: moderateScale(13),
    fontWeight: '700',
  },
  toolbar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#0f172a',
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(4),
    justifyContent: 'space-around',
    borderTopWidth: 1,
    borderTopColor: '#1e293b',
  },
  button: {
    backgroundColor: '#1e293b',
    borderRadius: moderateScale(8),
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(12),
    margin: moderateScale(4),
    borderWidth: 1,
    borderColor: '#334155',
  },
  buttonHighlight: {backgroundColor: '#dc2626', borderColor: '#ef4444'},
  buttonText: {
    color: '#94a3b8',
    fontSize: moderateScale(12),
    fontWeight: '600',
  },
  buttonTextHighlight: {color: '#ffffff'},
  gpsButton: {
    position: 'absolute',
    right: scale(16),
    bottom: verticalScale(154),
    width: scale(52),
    height: verticalScale(52),
    borderRadius: moderateScale(26),
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 999,
    elevation: moderateScale(8),
    shadowColor: '#3b82f6',
    shadowOffset: {width: 0, height: verticalScale(2)},
    shadowOpacity: 0.4,
    shadowRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  gpsButtonNavigating: {bottom: verticalScale(30)},
  reCenterButton: {
    position: 'absolute',
    right: scale(16),
    bottom: verticalScale(92),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    borderRadius: moderateScale(20),
    paddingVertical: verticalScale(8),
    paddingHorizontal: scale(14),
    zIndex: 999,
    elevation: moderateScale(8),
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.5)',
    shadowColor: '#3b82f6',
    shadowOffset: {width: 0, height: verticalScale(2)},
    shadowOpacity: 0.35,
    shadowRadius: moderateScale(6),
  },
  reCenterIcon: {
    color: '#3b82f6',
    fontSize: moderateScale(18),
    marginRight: scale(5),
    lineHeight: moderateScale(20),
  },
  reCenterLabel: {
    color: '#e2e8f0',
    fontSize: moderateScale(13),
    fontWeight: '600',
  },
  routeSummaryBar: {
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    paddingVertical: verticalScale(10),
    paddingHorizontal: scale(16),
    borderTopWidth: 1,
    borderTopColor: '#1e293b',
  },
  routeSummaryText: {
    color: '#e2e8f0',
    fontSize: moderateScale(13),
    fontWeight: '600',
    textAlign: 'center',
  },
});
